development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  pool: 5 #=>configuring the app to use a postgresql database in production since Sqlite isn't supported under Heroku
  